### ISSUE TITLE
Looking forward to some documentation on loops etc

### ISSUE THREAD

**Issue by Nagendracv** [axuno/Axuno.TextTemplating#1]

**Comment by axunonb** [comment]
`TextTemplating` is a very young project that we put into open source. Our primary target was a first production release, and docs will follow as soon as we find the time. `TextTemplating` is based on the [Scriban](https://github.com/lunet-io/scriban) language, which is well documented. Same as in your HandleBars project, we just link to the existing language description of Scriban.
