### ISSUE TITLE
What's the prescribed way of getting a reference to the Context objects?

### ISSUE THREAD

**Issue by Joebeazelman** [axuno/Axuno.TextTemplating#4]
I am trying to get the include option to work, but I will need to make a change to the TemplateContext.  I was under the false impression that the VirtualFileProviders handles it automatically. What's the prescribed way to get include to work?

**Comment by axunonb** [comment]
The [Wiki](https://github.com/axuno/TextTemplating/wiki#the-template-content) or unit test code didn't help?
A code sample would be helpful.

**Comment by Joebeazelman** [comment]
I don't mean TemplateContent but "TemplateContext." Are they the same thing?

**Comment by axunonb** [comment]
Guess you're talking about [Scriban.TemplateContest](https://github.com/scriban/scriban/blob/e2849b7bd1a014df2b7a899e4f96126612c06453/src/Scriban/TemplateContext.cs). So you're asking about how to use Scriban. [Please visit their website.](https://github.com/scriban/scriban).

**Comment by axunonb** [comment]
No response
